apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: wpdemo
type: Opaque
data:
  password: RGVtbzEyMzQ1IQo=
  root_password: RGVtbzEyMzQ1IQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app: wpdemo
type: Opaque
data:
  password: RGVtbzEyMzQ1IQo=